name: RandomTest
channels:
  - cvxgrp
  - conda-forge
  - conda-forge/label/gcc7
  - defaults
dependencies:
  - bzip2=1.0.6=1
  - future=0.17.0=py36_1000
  - lapack=3.6.1=1
  - osqp=0.4.1=py36hf8a1672_1
  - cvxpy=1.0.10=py36h0a44026_1001
  - cvxpy-base=1.0.10=py36h0a44026_1001
  - cvxcanon=0.1.1=py36_0
  - ecos=2.0.5=py36hf9b3073_0
  - multiprocess=0.70.4=py36_0
  - scs=1.2.6=py36_0
  - appnope=0.1.0=py36hf537a9a_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.0.2=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py36_0
  - cycler=0.10.0=py36hfc81398_0
  - decorator=4.3.0=py36_0
  - dill=0.2.8.2=py36_0
  - entrypoints=0.2.3=py36_2
  - fastcache=1.0.2=py36h1de35cc_2
  - freetype=2.9.1=hb4e5f40_0
  - intel-openmp=2019.0=118
  - ipykernel=5.1.0=py36h39e3cac_0
  - ipython=7.1.1=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - jedi=0.13.1=py36_0
  - jinja2=2.10=py36_0
  - jsonschema=2.6.0=py36hb385e00_0
  - jupyter_client=5.2.3=py36_0
  - jupyter_core=4.4.0=py36_0
  - kiwisolver=1.0.1=py36h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - libgcc=4.8.5=1
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.35=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - markupsafe=1.0=py36h1de35cc_1
  - matplotlib=3.0.1=py36h54f8f79_0
  - mistune=0.8.4=py36h1de35cc_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py36hb8a8100_0
  - mkl_random=1.0.1=py36h5d10147_1
  - nb_conda=2.2.1=py36_0
  - nb_conda_kernels=2.2.0=py36_0
  - nbconvert=5.3.1=py36_0
  - nbformat=4.4.0=py36h827af21_0
  - ncurses=6.1=h0a44026_0
  - nose=1.3.7=py36_2
  - notebook=5.7.0=py36_0
  - numpy=1.15.4=py36h6a91979_0
  - numpy-base=1.15.4=py36h8a80b8c_0
  - openssl=1.1.1=h1de35cc_0
  - pandas=0.23.4=py36h6440ff4_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.3.1=py36_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pip=18.1=py36_0
  - prometheus_client=0.4.2=py36_0
  - prompt_toolkit=2.0.7=py36_0
  - ptyprocess=0.6.0=py36_0
  - pygments=2.2.0=py36h240cd3f_0
  - pyparsing=2.3.0=py36_0
  - python=3.6.7=haf84260_0
  - python-dateutil=2.7.5=py36_0
  - pytz=2018.7=py36_0
  - pyzmq=17.1.2=py36h1de35cc_0
  - readline=7.0=h1de35cc_5
  - scikit-learn=0.20.1=py36h4f467ca_0
  - scipy=1.1.0=py36h28f7352_1
  - send2trash=1.5.0=py36_0
  - setuptools=40.5.0=py36_0
  - six=1.11.0=py36_1
  - sqlite=3.25.2=ha441bb4_0
  - terminado=0.8.1=py36_1
  - testpath=0.4.2=py36_0
  - tk=8.6.8=ha441bb4_0
  - toolz=0.9.0=py36_0
  - tornado=5.1.1=py36h1de35cc_0
  - traitlets=4.3.2=py36h65bd3ce_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - webencodings=0.5.1=py36_1
  - wheel=0.32.2=py36_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.2.5=h0a44026_1
  - zlib=1.2.11=hf3cbc9b_2
prefix: /anaconda3/envs/FullLib

